# -*- coding: utf-8 -*-
"""Industria_Textil.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oCyYIOoF0HfHg9Bbo0QeDOsQq7CB4Loj
"""

import numpy as np
import pandas as pd
import seaborn as sns

import tensorflow as tf
from tensorflow import keras
from keras import regularizers
from keras import Sequential
from keras.layers import Dense, Dropout
import matplotlib.pyplot as plt

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

from sklearn.metrics import r2_score
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import ExtraTreesRegressor


data = pd.read_csv('garments_worker_productivity.csv')

# Feature Engineering
def create_features_sweing(df):
    df = df.copy()
    df['department'] = df['department'].str.strip()
    df = df.drop('quarter', axis=1)
    df = df.dropna(subset=["wip"])

    df['date'] = pd.to_datetime(df['date'])
    df['ordinal_date'] = df['date'].apply(lambda x: x.toordinal())

    # Features derivadas
    df['theoretical_productivity'] = df['smv'] * df['no_of_workers']
    df['incentive_ratio'] = df['incentive'] / (df['over_time'] + 1)
    df['workload_per_worker'] = df['smv'] / (df['no_of_workers'] + 1)
    df['style_change_rate'] = df['no_of_style_change'] / (df['no_of_workers'] + 1)
    df['time_per_operation'] = df['over_time'] / (df['no_of_workers'] + 1)
    df['incentive_smv_interaction'] = df['incentive'] * df['smv']
    df['workers_overtime_interaction'] = df['no_of_workers'] * df['over_time']

    df = df.drop('date', axis=1)
    return df

data_sweing = create_features_sweing(data)

import pandas as pd
import numpy as np

def create_features_finishing(df):
    df = df.copy()

    # Normaliza y filtra finishing
    df["department"] = df["department"].astype(str).str.strip()
    df = df[df["department"].str.lower() != "sweing"].copy()

    # Drop columnas sin señal en finishing
    df = df.drop(["idle_time", "idle_men", "no_of_style_change", "wip", "quarter"], axis=1, errors="ignore")

    # Fecha -> ordinal
    df["date"] = pd.to_datetime(df["date"], errors="coerce")
    df = df.dropna(subset=["date"])  # por si hubiera fechas malas
    df["ordinal_date"] = df["date"].map(lambda x: x.toordinal())

    # Features derivadas (protegiendo divisiones)
    workers = df["no_of_workers"].astype(float)
    ot = df["over_time"].astype(float)
    smv = df["smv"].astype(float)
    inc = df["incentive"].astype(float)

    df["theoretical_productivity"] = smv * workers
    df["incentive_ratio"] = inc / (ot + 1.0)
    df["workload_per_worker"] = smv / (workers + 1.0)
    df["time_per_operation"] = ot / (workers + 1.0)
    df["workers_overtime_interaction"] = workers * ot

    # Si incentive casi siempre es 0 en finishing, a veces ayuda más así:
    df["has_incentive"] = (df["incentive"] > 0).astype(int)
    # Opcional: si usas has_incentive, puedes dropear incentive:
    # df = df.drop("incentive", axis=1)

    df = df.drop("date", axis=1)
    return df

data_finishing = create_features_finishing(data)

data_finishing.head(5)

TARGET = 'actual_productivity'
y_sweing = data_sweing[TARGET].values
X_sweing = data_sweing.drop(TARGET, axis=1)

y_finishing = data_finishing[TARGET].values
X_finishing = data_finishing.drop(TARGET, axis=1)

# Definir columnas EXCLUYENDO el target
categorical_cols = ['department', 'day']

# Numerical columns for sweing dataset
numerical_cols_sweing = [col for col in X_sweing.columns if col not in categorical_cols]

# Numerical columns for finishing dataset
numerical_cols_finishing = [col for col in X_finishing.columns if col not in categorical_cols]

# Train/test split sobre datos sin transformar
X_train_sweing, X_test_sweing, y_train_sweing, y_test_sweing = train_test_split(
    X_sweing, y_sweing, test_size=0.2, random_state=42
)

X_train_finishing, X_test_finishing, y_train_finishing, y_test_finishing = train_test_split(
    X_finishing, y_finishing, test_size=0.2, random_state=42
)

from sklearn.preprocessing import RobustScaler

# Pipeline para numéricas
numerical_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', RobustScaler(quantile_range=(25.0, 75.0)))
])

# Pipeline para categóricas
categorical_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

# Combinar ambos para sweing
preprocessor_sweing = ColumnTransformer(
    transformers=[
        ('num', numerical_pipeline, numerical_cols_sweing),
        ('cat', categorical_pipeline, categorical_cols)
    ],
    remainder='drop'
)

# Combinar ambos para finishing
preprocessor_finishing = ColumnTransformer(
    transformers=[
        ('num', numerical_pipeline, numerical_cols_finishing),
        ('cat', categorical_pipeline, categorical_cols)
    ],
    remainder='drop'
)

# Ajustar SOLO con train
X_train_preprocessed_sweing = preprocessor_sweing.fit_transform(X_train_sweing)
X_test_preprocessed_sweing = preprocessor_sweing.transform(X_test_sweing)

# Preprocesar finishing data (fit on train, transform on test)
X_train_preprocessed_finishing = preprocessor_finishing.fit_transform(X_train_finishing)
X_test_preprocessed_finishing = preprocessor_finishing.transform(X_test_finishing)

from sklearn.ensemble import IsolationForest
# Para sweing
iso_forest_sweing = IsolationForest(
    contamination=0.02,
    random_state=42,
    n_estimators=100,
    n_jobs=-1
)
outlier_labels_sweing = iso_forest_sweing.fit_predict(X_train_preprocessed_sweing)
inlier_mask_sweing = outlier_labels_sweing == 1
X_train_clean_sweing = X_train_preprocessed_sweing[inlier_mask_sweing]
y_train_clean_sweing = y_train_sweing[inlier_mask_sweing]

# Para finishing
iso_forest_finishing = IsolationForest(
    contamination=0.01,
    random_state=42,
    n_estimators=100,
    n_jobs=-1
)
outlier_labels_finishing = iso_forest_finishing.fit_predict(X_train_preprocessed_finishing)
inlier_mask_finishing = outlier_labels_finishing == 1
X_train_clean_finishing = X_train_preprocessed_finishing[inlier_mask_finishing]
y_train_clean_finishing = y_train_finishing[inlier_mask_finishing]

print(f"Sweing train size after outlier removal: {X_train_clean_sweing.shape}")
print(f"Finishing train size after outlier removal: {X_train_clean_finishing.shape}")

print("\n=== Finishing Target Distribution ===")
print(f"y_train_clean mean: {np.mean(y_train_clean_finishing):.4f}, std: {np.std(y_train_clean_finishing):.4f}")
print(f"y_train_clean min: {np.min(y_train_clean_finishing):.4f}, max: {np.max(y_train_clean_finishing):.4f}")
print(f"y_test mean: {np.mean(y_test_finishing):.4f}, std: {np.std(y_test_finishing):.4f}")
print(f"y_test min: {np.min(y_test_finishing):.4f}, max: {np.max(y_test_finishing):.4f}")

import pandas as pd
# Reconstruir DataFrame con features y target para análisis
df_check = pd.DataFrame(X_train_clean_finishing,
                        columns=preprocessor_finishing.get_feature_names_out())
df_check['target'] = y_train_clean_finishing

# Correlaciones
correlations = df_check.corr()['target'].sort_values(ascending=False)
print("\n=== Top correlations with target (Finishing) ===")
print(correlations.head(10))

def r2_score(y_true, y_pred):
    # Asegurar que las formas coincidan
    y_true = tf.reshape(y_true, [-1])
    y_pred = tf.reshape(y_pred, [-1])

    # Calcular de manera numéricamente estable
    SS_res = tf.reduce_sum(tf.square(y_true - y_pred))
    SS_tot = tf.reduce_sum(tf.square(y_true - tf.reduce_mean(y_true)))

    # Evitar división por cero y valores absurdos
    r2 = 1 - (SS_res / (SS_tot + tf.keras.backend.epsilon()))

    # Limitar el rango para evitar valores extremos
    return tf.clip_by_value(r2, -100, 100)  # Límite razonable

from keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint

callbacks = [
    EarlyStopping(
        monitor='val_loss',
        patience=50,
        min_delta=0.0001,
        restore_best_weights=True,
        verbose=1
    ),
    ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.5,
        patience=20,
        min_lr=1e-6,
        verbose=1
    ),
    ModelCheckpoint(
        'best_model.keras',
        monitor='val_r2_score',
        mode='max',
        save_best_only=True,
        verbose=1
    )
]

from keras.regularizers import l1_l2, l1, l2
from keras.layers import BatchNormalization, Input

# Optimizador con programación de tasa de aprendizaje
from keras.optimizers import Adam
from tensorflow.keras.metrics import R2Score

number_features_sweing = X_train_clean_sweing.shape[1]

# Model for sweing data
model_sweing = Sequential([
    Input(shape=(number_features_sweing,)), # Explicit Input Layer
    Dense(64, activation='relu',
          kernel_regularizer=l2(l2=0.01)),
    BatchNormalization(),
    Dense(32, activation='relu',
          kernel_regularizer=l2(l2=0.01)),
    BatchNormalization(),
    Dense(16, activation='relu'),
    Dense(1, activation='linear')
])

model_sweing.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='huber',
    metrics=['mae', R2Score(name='r2_score')]  # Métrica stateful
)

from sklearn.ensemble import GradientBoostingRegressor

gbr_sweing = GradientBoostingRegressor(n_estimators=200, max_depth=4, random_state=42)
gbr_sweing.fit(X_train_clean_sweing, y_train_clean_sweing)

y_pred_train_gbr = gbr_sweing.predict(X_train_clean_sweing)
r2_train_gbr = r2_score(y_train_clean_sweing, y_pred_train_gbr)
print(f"GradientBoosting R² train: {r2_train_gbr:.4f}")

from sklearn.model_selection import GridSearchCV

# Base model for GridSearchCV
base_gbr_finishing = GradientBoostingRegressor(random_state=42)

# Parameter grid to search for finishing data
param_grid_finishing = {
    'n_estimators': [100, 200, 300],
    'learning_rate': [0.01, 0.05, 0.1],
    'max_depth': [3, 4, 5, 6],
    'subsample': [0.7, 0.8, 0.9]
}

# Initialize GridSearchCV
grid_search = GridSearchCV(
    estimator=base_gbr_finishing,
    param_grid=param_grid_finishing,
    cv=5,
    scoring='r2',
    n_jobs=-1,
    verbose=1
)

from sklearn.metrics import r2_score, mean_squared_error

# Fit GridSearchCV to find the best parameters and model
grid_search.fit(X_train_clean_finishing, y_train_clean_finishing)

# Entrenar con mejores parámetros del GridSearch
best_model = grid_search.best_estimator_
print(f"Mejores parámetros: {grid_search.best_params_}")

# Evaluar en ambos conjuntos
y_pred_train = best_model.predict(X_train_clean_finishing)
y_pred_test = best_model.predict(X_test_preprocessed_finishing)

r2_train = r2_score(y_train_clean_finishing, y_pred_train)
r2_test = r2_score(y_test_finishing, y_pred_test)

mse_train = mean_squared_error(y_train_clean_finishing, y_pred_train)
mse_test = mean_squared_error(y_test_finishing, y_pred_test)

print(f"\n=== Métricas Finishing ===")
print(f"R² train: {r2_train:.4f}")
print(f"R² test:  {r2_test:.4f}")
print(f"Diferencia: {abs(r2_train - r2_test):.4f}")
print(f"\nMSE train: {mse_train:.4f}")
print(f"MSE test:  {mse_test:.4f}")

gbr_finishing = best_model

# Modelo neuronal
print("Training model for sweing data...")
training_history_sweing = model_sweing.fit(
    X_train_clean_sweing, y_train_clean_sweing,
    epochs=500,
    verbose = 0,
    callbacks = callbacks,
    validation_split=0.2
)

from sklearn.metrics import r2_score

# --- Sweing Models --- #
# Gradient Boosting Regressor for sweing
y_pred_gbr_sweing_test = gbr_sweing.predict(X_test_preprocessed_sweing)
r2_gbr_sweing_test = r2_score(y_test_sweing, y_pred_gbr_sweing_test)

# Keras Neural Network for sweing
y_pred_nn_sweing_test = model_sweing.predict(X_test_preprocessed_sweing).flatten()
r2_nn_sweing_test = r2_score(y_test_sweing, y_pred_nn_sweing_test)

# --- Finishing Model --- #
# Gradient Boosting Regressor for finishing
y_pred_gbr_finishing_test = gbr_finishing.predict(X_test_preprocessed_finishing)
r2_gbr_finishing_test = r2_score(y_test_finishing, y_pred_gbr_finishing_test)

print("=== R2 Scores on Test Data ===")
print(f"Sweing GBR R2: {r2_gbr_sweing_test:.4f}")
print(f"Sweing Neural Network R2: {r2_nn_sweing_test:.4f}")
print(f"Finishing GBR R2: {r2_gbr_finishing_test:.4f}")

def plot_training_history(history, title_suffix):
    history_dict = history.history

    plt.figure(figsize=(12, 5))

    # Plot Loss
    plt.subplot(1, 2, 1)
    plt.plot(history_dict['loss'], label='Training Loss')
    plt.plot(history_dict['val_loss'], label='Validation Loss')
    plt.title(f'Loss over Epochs ({title_suffix})')
    plt.xlabel('Epochs')
    plt.ylabel('Loss (Huber)')
    plt.legend()
    plt.grid(True)

    # Plot R2 Score
    plt.subplot(1, 2, 2)
    plt.plot(history_dict['r2_score'], label='Training R2 Score')
    plt.plot(history_dict['val_r2_score'], label='Validation R2 Score')
    plt.title(f'R2 Score over Epochs ({title_suffix})')
    plt.xlabel('Epochs')
    plt.ylabel('R2 Score')
    plt.legend()
    plt.grid(True)

    plt.tight_layout()
    plt.show()

plot_training_history(training_history_sweing, 'Sweing Data')

print("Predictions for Sweing Data (sample from X_test_sweing):")
predictions_sweing = model_sweing.predict(X_test_preprocessed_sweing)

for i in range(min(20, len(predictions_sweing))): # Print first 10 predictions
    print(f'model prediction: {predictions_sweing[i][0]:.4f}, actual: {y_test_sweing[i]:.4f}')

predictions_sweing_gbr = gbr_sweing.predict(X_test_preprocessed_sweing)

for i in range(min(20, len(predictions_sweing_gbr))): # Print first 10 predictions
  print(f'gbr model: {predictions_sweing_gbr[i]:.4f}, actual: {y_test_sweing[i]:.4f}')

print("Prediction for finishing Data")
predictions_finishing = gbr_finishing.predict(X_test_preprocessed_finishing)

for i in range(min(10, len(predictions_finishing))): # Print first 10 predictions
    print(f'model prediction: {predictions_finishing[i]:.4f}, actual: {y_test_finishing[i]:.4f}')